# Generated by Django 5.0.2 on 2024-03-02 18:16

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('firmware_file', models.FileField(upload_to='firmwares/')),
                ('version', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('capture_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoTrap',
            fields=[
                ('mac_address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ntp_url', models.CharField(default='pool.ntp.org', max_length=255)),
                ('gmt_offset', models.IntegerField(default=-3)),
                ('daylight_offset', models.IntegerField(default=0)),
                ('movement_sensor', models.BooleanField(default=False)),
                ('restart', models.BooleanField(default=False)),
                ('photo_shooting_frequency', models.CharField(default='["00:00","12:00"]', max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('floor', models.FloatField(default=0.0)),
                ('photo_url', models.CharField(default='177.73.234.198', max_length=255)),
                ('photo_path', models.CharField(default='/photos/', max_length=255)),
                ('photo_port', models.IntegerField(default=88)),
                ('firmware_url', models.CharField(default='https://raw.githubusercontent.com/FernandoVinha/api_rato/main/', max_length=255)),
                ('firmware_path', models.CharField(default='get_test_09.ino.esp32.bin', max_length=255)),
                ('install_new_firmware', models.BooleanField(default=True)),
                ('country', django_countries.fields.CountryField(default='BR', max_length=2)),
                ('status', models.IntegerField(choices=[(0, 'Offline'), (1, 'With Issues'), (2, 'Attention Needed'), (3, 'Operational')], default=3)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
            ],
        ),
    ]
