# Generated by Django 5.0.2 on 2024-03-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('photo_trap', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototrap',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company'),
        ),
        migrations.AddField(
            model_name='phototrap',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AddField(
            model_name='phototrap',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_trap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_trap.phototrap'),
        ),
        migrations.AddField(
            model_name='firmware',
            name='compatible_devices',
            field=models.ManyToManyField(to='photo_trap.phototrap'),
        ),
    ]
